-- 组函数 AVG COUNT MAX MIN SUM
-- AVG SUM 只能是数字
SELECT AVG(SALARY),SUM(SALARY) from EMPLOYEES
SELECT MIN(SALARY),MAX(SALARY) from EMPLOYEES
SELECT MIN(LAST_NAME),MAX(LAST_NAME) from EMPLOYEES
SELECT MIN(HIRE_DATE),MAX(HIRE_DATE) from EMPLOYEES
SELECT DEPARTMENT_ID, AVG(SALARY) from EMPLOYEES GROUP BY DEPARTMENT_ID
SELECT COUNT(*) FROM EMPLOYEES WHERE LAST_NAME LIKE '%a%'
-- COUNT(expr) 列名 计算不为空
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES WHERE DEPARTMENT_ID=80
-- COUNT(expr) 列名 计算不为空 DISTINCT 剔除重复
SELECT COUNT(DISTINCT DEPARTMENT_ID) from EMPLOYEES --11