-- 组函数 AVG COUNT MAX MIN SUM
-- AVG SUM 只能是数字
SELECT AVG(SALARY),SUM(SALARY) from EMPLOYEES
SELECT MIN(SALARY),MAX(SALARY) from EMPLOYEES
SELECT MIN(LAST_NAME),MAX(LAST_NAME) from EMPLOYEES
SELECT MIN(HIRE_DATE),MAX(HIRE_DATE) from EMPLOYEES
SELECT DEPARTMENT_ID, AVG(SALARY) from EMPLOYEES GROUP BY DEPARTMENT_ID
SELECT COUNT(*) FROM EMPLOYEES WHERE LAST_NAME LIKE '%a%'
-- COUNT(expr) 列名 计算不为空
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES WHERE DEPARTMENT_ID=80
-- COUNT(expr) 列名 计算不为空 DISTINCT 剔除重复
SELECT COUNT(DISTINCT DEPARTMENT_ID) from EMPLOYEES --11
-- NVL(expr1, expr2) 使空值也参加运算
SELECT AVG(NVL(COMMISSION_PCT, 0)) from EMPLOYEES
-- GROUP BY 不能用字段别名，可以用表别名  SELECT和order by的字段必须在groupby中
SELECT DEPARTMENT_ID, AVG(SALARY) from EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) from EMPLOYEES GROUP BY DEPARTMENT_ID,JOB_ID  ORDER BY DEPARTMENT_ID, SUM(SALARY)
SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000
SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000
-- 嵌套组函数
SELECT MAX(AVG(SALARY)) from EMPLOYEES GROUP BY DEPARTMENT_ID

-- 练习
select MAX(SALARY),MIN(SALARY),AVG(SALARY) from EMPLOYEES GROUP BY JOB_ID
select JOB_ID,COUNT(*) from EMPLOYEES GROUP BY JOB_ID
select COUNT(DISTINCT MANAGER_ID) from EMPLOYEES
SELECT MANAGER_ID,MIN(SALARY) from EMPLOYEES WHERE MANAGER_ID is not null GROUP BY MANAGER_ID HAVING MIN(SALARY)> 6000 ORDER BY MIN(SALARY)
SELECT d.DEPARTMENT_NAME,d.LOCATION_ID,COUNT(*),avg(e.SALARY) from EMPLOYEES e, DEPARTMENTS d WHERE e.DEPARTMENT_ID=d.DEPARTMENT_ID GROUP BY d.DEPARTMENT_NAME, d.LOCATION_ID
-- SUM(expr)
select count(*) total,sum(decode(to_char(hire_date,'yyyy'),'2000',1,0))"2000" ,sum(decode(to_char(hire_date,'yyyy'),'2001',1,0))"2001",
sum(decode(to_char(hire_date,'yyyy'),'2002',1,0))"2002",sum(decode(to_char(hire_date,'yyyy'),'2003',1,0))"2003" from employees e;

select job_id,sum(salary),
sum(decode(department_id,20,salary))"Dep20",
sum(decode(department_id,50,salary))"Dep50",
sum(decode(department_id,80,salary))"Dep80" ,
sum(decode(department_id,90,salary))"Dep 90" 
from employees group by job_id;






