-- select

-- 表达式
select EMPLOYEE_ID,FIRST_NAME, SALARY, (SALARY*12+100) as SALARY from EMPLOYEES
select EMPLOYEE_ID,FIRST_NAME, SALARY, (SALARY+100)*12 as SALARY from EMPLOYEES

-- 空值计算返回都是空
select EMPLOYEE_ID,FIRST_NAME, SALARY, (SALARY*12*COMMISSION_PCT) SALARY from EMPLOYEES 

-- 别名可以用as或者空格，小写自动转成大写
select EMPLOYEE_ID,FIRST_NAME, SALARY, COMMISSION_PCT comm from EMPLOYEES 
-- 别名有特殊符号，需要用双引号，不会自动转成大写
select EMPLOYEE_ID,FIRST_NAME, SALARY*12 "Annual Salary" from EMPLOYEES 

-- 连接符
select LAST_NAME || FIRST_NAME from EMPLOYEES 
select LAST_NAME || SALARY, LAST_NAME || 12*SALARY from EMPLOYEES
select LAST_NAME || JOB_ID as "Employee" from EMPLOYEES

-- 文字字符串 单引号
select LAST_NAME || ' is a ' || JOB_ID as "Employee Details" from EMPLOYEES
select LAST_NAME || 55 || JOB_ID as "Employee Details" from EMPLOYEES

-- 去除重复行
select DISTINCT DEPARTMENT_ID from EMPLOYEES
-- DISTINCT作用后面所有字段
select DISTINCT DEPARTMENT_ID,LAST_NAME from EMPLOYEES ORDER BY LAST_NAME

--where 约束
select LAST_NAME,JOB_ID,DEPARTMENT_ID from EMPLOYEES WHERE DEPARTMENT_ID=90
--字符串和日期 单引号 大小写敏感 DD-MON-RR 日月年  月：1月/jan
SELECT JOB_ID from EMPLOYEES where LAST_NAME='King'
select LAST_NAME,DEPARTMENT_ID,JOB_ID from EMPLOYEES where HIRE_DATE='24-jan-2006'
-- = > < <= >= <>
SELECT * from EMPLOYEES where SALARY<=3000
-- BETWEEN AND
select LAST_NAME,SALARY from EMPLOYEES WHERE SALARY BETWEEN 2500 and 3500
-- IN
select LAST_NAME,SALARY,EMPLOYEE_ID,MANAGER_ID from EMPLOYEES where MANAGER_ID IN (100,101,201)
-- LIKE 匹配符% 占位符 _  转义符 ESCAPE
SELECT	LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%'
SELECT	LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '_a%' --第2个是a的
SELECT	LAST_NAME,HIRE_DATE FROM EMPLOYEES where HIRE_DATE like '%05'
SELECT LAST_NAME,JOB_ID from EMPLOYEES where JOB_ID like 'SA\_%' ESCAPE '\' --告诉sql语句\是转义符号
-- is NULL
SELECT LAST_NAME,JOB_ID,COMMISSION_PCT from EMPLOYEES where COMMISSION_PCT is NOT NULL
-- AND OR NOT
SELECT EMPLOYEE_ID,JOB_ID,SALARY FROM EMPLOYEES WHERE JOB_ID LIKE '%MAN%' and SALARY>=10000
SELECT EMPLOYEE_ID,JOB_ID,SALARY FROM EMPLOYEES WHERE JOB_ID LIKE '%MAN%' or SALARY>=10000
SELECT LAST_NAME,JOB_ID from EMPLOYEES where JOB_ID not in ('IT_PROG','ST_CLERK','SA_REP')
-- 优先级从高到低
-- 算术 连字 比较 (is null like in)  BETWEEN not and or
select LAST_NAME,JOB_ID,SALARY from EMPLOYEES where JOB_ID='SA_REP' or JOB_ID='AD_PRES' AND SALARY>15000
select LAST_NAME,JOB_ID,SALARY from EMPLOYEES where (JOB_ID='SA_REP' or JOB_ID='AD_PRES') AND SALARY>15000

-- ORDER BY 默认 升序 ASC 降序 DESC 可以指定没有投影的字段
-- 字符值顺序 A-Z
-- ASC 空值在最后 DESC 空值在开始
SELECT LAST_NAME from EMPLOYEES ORDER BY SALARY ASC
SELECT LAST_NAME,HIRE_DATE,SALARY,COMMISSION_PCT from EMPLOYEES order by HIRE_DATE
-- 别名排序
SELECT LAST_NAME as name,HIRE_DATE,SALARY,COMMISSION_PCT from EMPLOYEES order by name
-- 两个列排序 先排第一个，中间用第二个，单个列表可以加asc或desc
SELECT HIRE_DATE, SALARY from EMPLOYEES ORDER BY HIRE_DATE,SALARY
SELECT HIRE_DATE, SALARY from EMPLOYEES ORDER BY HIRE_DATE,SALARY desc



















